import type { Agent, Hook } from "../core/schema.ts";
import type { TargetId } from "../core/types.ts";

export interface AgentDocument {
  agent: Agent;
  content: string;
  tools?: string[];
}

export const AMP_PLUGIN_EVENT_MAP: Partial<Record<Hook["event"], string>> = {
  before_tool: "tool.call",
  after_tool: "tool.result",
  session_start: "session.start",
  before_agent: "agent.start",
  after_agent: "agent.end",
};

export const PI_PLUGIN_EVENT_MAP: Partial<Record<Hook["event"], string>> = {
  before_tool: "tool_call",
  after_tool: "tool_result",
  session_start: "session_start",
  session_end: "session_shutdown",
  before_agent: "before_agent_start",
  before_compact: "session_before_compact",
  stop: "agent_end",
};

export function hookRegistryJson(hooks: Hook[]): string {
  return `${JSON.stringify({ version: 1, hooks }, null, 2)}\n`;
}

export function hookRunnerSource(): string {
  return `#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const runtimeDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(runtimeDir, "../..");
let registry;
try { registry = JSON.parse(fs.readFileSync(path.join(runtimeDir, "hooks.json"), "utf8")); }
catch { process.exit(0); }
const hooks = Array.isArray(registry?.hooks) ? registry.hooks : [];
const args = process.argv.slice(2);
const arg = (name) => { const index = args.indexOf(name); return index >= 0 ? args[index + 1] : undefined; };
const hookId = arg("--hook");
const target = arg("--target") || "unknown";
const event = arg("--event") || "unknown";
const hook = hooks.find((candidate) => candidate.id === hookId && candidate.enabled !== false);
if (!hook) process.exit(0);

let rawText = "";
try { rawText = fs.readFileSync(0, "utf8"); } catch { rawText = ""; }
let raw;
try { raw = rawText.trim() ? JSON.parse(rawText) : {}; } catch { raw = { raw: rawText }; }
const toolName = String(raw.tool_name ?? raw.toolName ?? raw.tool ?? raw.name ?? raw.input?.tool ?? raw.input?.toolName ?? "");
const toolInput = raw.tool_input ?? raw.toolInput ?? raw.input ?? raw.args ?? {};
const serialized = JSON.stringify({ toolName, toolInput, raw });

const capabilityPatterns = {
  shell: /(bash|shell|terminal|execute|exec|command|run_command)/i,
  read: /(read|view|cat|glob|grep|search|list|find)/i,
  write: /(write|edit|patch|create|delete|move|replace)/i,
  search: /(grep|glob|search|find|list)/i,
  web: /(web|fetch|browser|http)/i,
  mcp: /(mcp|server)/i,
  subagent: /(task|agent|subagent)/i,
  test: /(test|spec|check|verify)/i,
  git: /(git|commit|branch|diff|push|pull)/i,
};
const matchesTool = !hook.matcher?.tools?.length || hook.matcher.tools.some((name) => {
  if (name === toolName) return true;
  try { return new RegExp(name).test(toolName); } catch { return false; }
});
const matchesCapability = !hook.matcher?.capabilities?.length || hook.matcher.capabilities.some((capability) => capabilityPatterns[capability]?.test(toolName));
let matchesInput = true;
if (hook.matcher?.inputRegex) {
  try { matchesInput = new RegExp(hook.matcher.inputRegex).test(serialized); }
  catch (error) { console.error(\`Invalid inputRegex for hook \${hook.id}: \${error.message}\`); process.exit(2); }
}
if (!matchesTool || !matchesCapability || !matchesInput) process.exit(0);

const normalized = {
  version: 1,
  hookId: hook.id,
  target,
  event,
  repositoryRoot: repoRoot,
  toolName,
  toolInput,
  raw,
};
const [command, ...commandArgs] = hook.run;
const result = spawnSync(command, commandArgs, {
  cwd: repoRoot,
  env: {
    ...process.env,
    CANONFIG_ROOT: repoRoot,
    CANONFIG_HOOK_ID: hook.id,
    CANONFIG_TARGET: target,
    CANONFIG_EVENT: event,
    CANONFIG_TOOL_NAME: toolName,
  },
  input: JSON.stringify(normalized),
  encoding: "utf8",
  timeout: hook.timeoutMs,
  maxBuffer: 16 * 1024 * 1024,
});

let output;
try { output = result.stdout?.trim() ? JSON.parse(result.stdout) : undefined; } catch { output = undefined; }
const reason = String(output?.reason ?? result.stderr?.trim() ?? result.error?.message ?? \`Canonfig hook \${hook.id} failed\`);
const denied = result.status === 2 || output?.decision === "deny" || output?.permission === "deny" || output?.block === true;
const failed = result.error || result.status === null || (result.status !== 0 && result.status !== 2);
if (denied || (failed && hook.onFailure === "block")) {
  console.error(reason);
  process.exit(2);
}
if (failed && hook.onFailure === "warn") console.error(reason);
if (output?.message) console.log(String(output.message));
else if (result.stdout && !output) process.stdout.write(result.stdout);
process.exit(0);
`;
}

function pluginPreamble(target: TargetId): string {
  return `// Generated by Canonfig. Edit the active .canonfig/harness configuration instead.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execFile } from "node:child_process";

function findRoot() {
  let current = path.dirname(fileURLToPath(import.meta.url));
  while (true) {
    if (fs.existsSync(path.join(current, ".canonfig", ".runtime", "hook-runner.mjs"))) return current;
    const parent = path.dirname(current);
    if (parent === current) return process.cwd();
    current = parent;
  }
}
const root = findRoot();
function runCanonfig(hookId, event, payload, timeoutMs) {
  return new Promise((resolve) => {
    const runner = path.join(root, ".canonfig", ".runtime", "hook-runner.mjs");
    const child = execFile(
      process.execPath,
      [runner, "--hook", hookId, "--target", "${target}", "--event", event],
      {
        cwd: root,
        encoding: "utf8",
        timeout: Math.max(1, timeoutMs + 1000),
        maxBuffer: 16 * 1024 * 1024,
      },
      (error, stdout, stderr) => {
        const reason = String(stderr || stdout || error?.message || "Blocked by Canonfig hook").trim();
        resolve({ blocked: error !== null, reason });
      },
    );
    child.stdin?.on("error", () => {});
    child.stdin?.end(JSON.stringify(payload ?? {}));
  });
}
`;
}

export function ampPluginSource(hooks: Hook[], agents: AgentDocument[] = []): string {
  const enabled = hooks.filter((hook) => hook.enabled);
  const registrations = enabled.map((hook) => {
    const event = AMP_PLUGIN_EVENT_MAP[hook.event];
    if (!event) return "";
    const rejection = event === "tool.call"
      ? "if (result.blocked) return { action: \"reject-and-continue\", message: result.reason };"
      : "if (result.blocked) throw new Error(result.reason);";
    return `  amp.on(${JSON.stringify(event)}, async (payload) => { const result = await runCanonfig(${JSON.stringify(hook.id)}, ${JSON.stringify(hook.event)}, payload, ${hook.timeoutMs}); ${rejection} });`;
  }).filter(Boolean);

  const agentRegistrations = agents.flatMap(({ agent, content, tools }) => {
    const variable = `canonfigAgent_${agent.id.replaceAll(/[^A-Za-z0-9_$]/g, "_")}`;
    const toolName = `canonfig_${agent.id.replaceAll(/[^A-Za-z0-9_]/g, "_")}_subagent`;
    const definition = [
      `  const ${variable} = amp.createAgent({`,
      `    name: ${JSON.stringify(agent.id)},`,
      ...(agent.model === "inherit" ? [] : [`    model: ${JSON.stringify(agent.model)},`]),
      `    instructions: ${JSON.stringify(content.trim())},`,
      `    tools: ${tools?.length ? JSON.stringify(tools) : JSON.stringify("all")},`,
      `    display: { label: ${JSON.stringify(agent.id)} },`,
      "  });",
      "",
      "  amp.registerTool({",
      `    name: ${JSON.stringify(toolName)},`,
      `    description: ${JSON.stringify(agent.description)},`,
      "    inputSchema: { type: \"object\", properties: { request: { type: \"string\" } }, required: [\"request\"] },",
      "    async execute(input, ctx) {",
      "      const request = typeof input.request === \"string\" ? input.request : \"\";",
      "      if (!request.trim()) return \"Missing subagent request.\";",
      `      const result = await ${variable}.run(request, { parentThreadID: ctx.thread.id, timeoutMs: 10 * 60 * 1000 });`,
      "      return result.text;",
      "    },",
      "  });",
    ];
    return definition;
  });

  return `${pluginPreamble("amp")}\nimport type { PluginAPI } from "@ampcode/plugin";\n\nexport default function canonfig(amp: PluginAPI) {\n${[...registrations, ...agentRegistrations].join("\n")}\n}\n`;
}

export function piPluginSource(target: "pi" | "oh-my-pi", hooks: Hook[]): string {
  const registrations = hooks.filter((hook) => hook.enabled).map((hook) => {
    const event = PI_PLUGIN_EVENT_MAP[hook.event];
    if (!event) return "";
    const result = hook.event === "before_tool"
      ? "if (result.blocked) return { block: true, reason: result.reason };"
      : "if (result.blocked) throw new Error(result.reason);";
    return `  pi.on(${JSON.stringify(event)}, async (payload) => { const result = await runCanonfig(${JSON.stringify(hook.id)}, ${JSON.stringify(hook.event)}, payload, ${hook.timeoutMs}); ${result} });`;
  }).filter(Boolean).join("\n");
  const packageName = target === "pi" ? "@earendil-works/pi-coding-agent" : "@oh-my-pi/pi-coding-agent";
  return `${pluginPreamble(target)}\nimport type { ExtensionAPI } from ${JSON.stringify(packageName)};\n\nexport default function canonfig(pi: ExtensionAPI) {\n${registrations}\n}\n`;
}

export function openCodePluginSource(target: "opencode" | "kilo", hooks: Hook[]): string {
  const before = hooks.filter((hook) => hook.enabled && hook.event === "before_tool");
  const after = hooks.filter((hook) => hook.enabled && hook.event === "after_tool");
  const beforeBody = before.map((hook) => `      { const result = await runCanonfig(${JSON.stringify(hook.id)}, "before_tool", { ...input, ...output }, ${hook.timeoutMs}); if (result.blocked) throw new Error(result.reason); }`).join("\n");
  const afterBody = after.map((hook) => `      { const result = await runCanonfig(${JSON.stringify(hook.id)}, "after_tool", { ...input, ...output }, ${hook.timeoutMs}); if (result.blocked) throw new Error(result.reason); }`).join("\n");
  return `${pluginPreamble(target)}\nexport const CanonfigPlugin = async () => ({\n  "tool.execute.before": async (input, output) => {\n${beforeBody}\n  },\n  "tool.execute.after": async (input, output) => {\n${afterBody}\n  },\n});\n`;
}
